### ISSUE TITLE
New material system

### ISSUE THREAD

**Issue by phaazon** [phaazon/quaazar#45]
# Link between lights and materials

Lights and materials are tightly bound. A material can be seen as a function of light. Because we can’t generalize light, a material has to implement **all** kinds of lights.

So, what’s a `GPULight`? Well, it’s basically a function that will update itself into a `GPUMaterial`. Do we have to batch? I don’t think so. The `GPUMaterial` will have several interfaces (i.e. one per light kind) we’ll be able to use. The first one is of course the *ambient slot interface*. Then, when we commit stuff, we can simply send it via the slot so that it’s get updated.

**Comment by xtrium** [comment]
Holy crap ! :D

2015-01-23 11:02 GMT+01:00 Dimitri Sabadie <notifications@github.com>:

> Lighting
>
> Lighting is, at current revision
> <https://github.com/phaazon/photon/tree/1cf78bc93042704fc22ab82c1e88deeddcde913f>,
> implemented only in terms of Omni lighting. This is an issue because
> we’ll want several kinds of light be included among:
>
>    - ambient ligthing (see #26
>    <https://github.com/phaazon/photon/issues/26>)
>    - omnidirectional lighting, already implemented
>    - spot lighting (see #47 <https://github.com/phaazon/photon/issues/47>)
>    - etc.
>
> The idea of this change is to refactor the current lighting system to make
> it more about to include a new kind of light.
>  Light, GPULight, Lighting, Shadowing and Lit Light
>
> This is a mandatory core type used to represent lights. There’re a few
> functions to create lights.
> GPULight
>
> This type is less intuitive, yet very simple. It represents a Light on
> *GPU*, which is a piece of code plugged onto a render to make it lit. To
> understand that type, we have to understand what a Shaded object and
> Rendered objects are.
>
> A Rendered object represents a *rendered scene*. If you got a Rendered
> object, you know that it gathers at least one mesh – but it’ll almost
> always contain the whole scene – rendered.
>
> A Shaded object is a Rendered object with material information attached.
> A Shaded object has two basic primitives:
>
>    - runShaded, which simply executes the Shaded code
>    - runShadedNoMaterial, which executes the Shaded code discarding
>    materials
>
> runShadedNoMaterial can be useful when a higher level of abstraction
> needs to run a Shaded object but it doesn’t need materials (e.g. *shadow
> mapping*).
>
> Then, what does a GPULight actually do? Well, it runs a Shaded object
> with extra information around. For instance, a GPULight obtained via an
> Ambient light will simply add color and power information onto the Shaded
> object. How is this performed? A GPULight has access to a few other
> objects – which are generated by the renderer – so that it can does its
> job. A GPULight is just a function of Lighting, Shadowing and Accumulation
> and outputs a LitBatch. A LitBatch is a simple object used to batch
> lights so that we lighten the scene with all omnidirectional lights once,
> all ambient lights once, etc.
> Lighting
>
> This type is pretty convenient because it contains anything a light might
> want. It has shader programs, it has uniforms, it has shadowing
> information. It’s a *helper bridge to the renderer* lights can use to
> implement various kinds of effects.
> Shadowing
>
> This type is included in Lighting and expose *shadowing* concepts. For
> instance, it has programs and uniforms for omnidirectional lights and spot
> lights.
> Lit
>
> This type is the higher level of abstraction of lights. It’s an end-user
> type which is created by the lighten function.
> Future
>
> What happens if I suddenly spawn at the corner of a room and shouts:
>
> *— Holy shit! @xtrium <https://github.com/xtrium> added ultra cool area
> lights! I need the same thing!*
>
> How new lights integration works?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phaazon/photon/issues/45>.
>



-- 
Charles 'xtrium <http://xtrium.net/>' Bulckaen
 :: www.frequency.fr
 :: www.lnx-demo.org

**Comment by phaazon** [comment]
@xtrium sowhat? :D

**Comment by xtrium-lnx** [comment]
Holy shit dat old account oO

**Comment by phaazon** [comment]
Aaaah! I just got it!

**Comment by xtrium-lnx** [comment]
C'est bien, c'est explicite comme commit message, ça. :p

**Comment by phaazon** [comment]
Quoi donc ?

**Comment by phaazon** [comment]
Done as I’ve removed explicit materials. They’re now fully polymorphic, and so are shaders. \o/
